# Azure pipeline definition for the integration of the solution (continuous integration)
# See: https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr:
  autoCancel: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

schedules:
- cron: "0 0 * * *"
  displayName: 'Daily midnight build'
  branches:
    include:
    - master
  always: true

variables:
# library variable groups
- group: 'build-tools'
- group: 'integration-testing-sandbox'
# common task variables
- name: 'BuildConfiguration'
  value: 'Debug'
- name: 'SolutionFile'
  value: 'Devpro.Hubspot.sln'
- name: 'TestProjects'
  value: 'test/*Tests/*.csproj'
- name: 'UnitTestProjects'
  value: 'test/*UnitTests/*.csproj'
# tool variables (Sonar)
- name: 'sonar.project.name'
  value: 'HubSpot .NET Client'
- name: 'sonar.project.key'
  value: 'devpro.hubspot.dotnet'
# specific variables
- name: 'dotnet.sdk.version'
  value: '3.1.100'

# Unit testing
stages:
- stage: 'unit_testing'
  displayName: 'Unit testing'
  jobs:
  # Run on Linux (Ubuntu)
  - job: 'linuxci'
    displayName: 'Linux CI'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      displayName: 'Get latest .NET SDK'
      inputs:
        packageType: 'sdk'
        version: $(dotnet.sdk.version)
    - task: DotNetCoreCLI@2
      displayName: 'Build the dotnet solution'
      inputs:
        command: 'build'
        projects: $(SolutionFile)
        arguments: '-c $(BuildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: 'Run the dotnet tests'
      inputs:
        command: 'test'
        projects: $(UnitTestProjects)
        arguments: '-c $(BuildConfiguration) --collect:"XPlat Code Coverage"'
    - task: DotNetCoreCLI@2
      displayName: 'Install ReportGenerator global tool'
      inputs:
        command: custom
        custom: tool
        arguments: 'install -g dotnet-reportgenerator-globaltool'
    - script: 'reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"'
      displayName: 'Create the reports'
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish the code coverage'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml'
- stage: 'integration_testing'
  displayName: 'Integration testing'
  dependsOn: [] # mandatory to be able to run unit and integration testing stages in parallel
  jobs:
  - job: 'windows_integrationtests'
    displayName: 'Windows CI'
    pool:
      # code coverage generation only works on Windows for the moment
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: $(dotnet.sdk.version)
    - task: DotNetCoreCLI@2
      displayName: 'Restore .NET packages'
      inputs:
        command: 'restore'
        projects: '$(SolutionFile)'
        feedsToUse: 'select'
        noCache: $(dotnet.cache.disable)
    - task: SonarCloudPrepare@1
      displayName: 'Prepare code analysis'
      inputs:
        SonarCloud: '$(sonar.instance)'
        organization: '$(sonar.organization)'
        scannerMode: 'MSBuild'
        projectKey: '$(sonar.project.key)'
        projectName: '$(sonar.project.name)'
        extraProperties: |
          sonar.cpd.exclusions=**/Models/*.cs,**/Dto/*.cs
    - task: DotNetCoreCLI@2
      displayName: 'Build the .NET solution'
      inputs:
        command: 'build'
        projects: $(SolutionFile)
        arguments: '-c $(BuildConfiguration)'
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        COREHOST_TRACE: 0
    - task: DotNetCoreCLI@2
      displayName: 'Run all tests on .NET projects'
      inputs:
        command: 'test'
        projects: $(TestProjects)
        arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        COREHOST_TRACE: 0
        Yanport_Sandbox_BaseUrl: $(yanport.api.baseurl)
        Yanport_Sandbox_Token: $(yanport.api.token)
    - task: SonarCloudAnalyze@1
      displayName: 'Analyze the code with Sonar'
    - task: SonarCloudPublish@1
      displayName: 'Publish the code analysis results'
      inputs:
        pollingTimeoutSec: '300'
