version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Withywoods.WebTesting
    versions:
    - 1.4.1
  - dependency-name: Withywoods.UnitTesting
    versions:
    - 1.4.1
  - dependency-name: Withywoods.Serialization
    versions:
    - 1.4.1
  - dependency-name: Withywoods.Selenium
    versions:
    - 1.4.1
  - dependency-name: Withywoods.AspNetCore
    versions:
    - 1.4.1
  - dependency-name: Microsoft.AspNetCore.Mvc.Testing
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Selenium.WebDriver.ChromeDriver
    versions:
    - 88.0.4324.9600
    - 89.0.4389.2300
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
  - dependency-name: Moq
    versions:
    - 4.16.0
